spring:
  application:
    name: springboot-redis-examples
  redis:
    host: localhost
    port: 56379
    database: 0
    timeout: 20s
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms