version: "3.9"
services:
  ## `redis-5.0.10.conf`
  # protected-mode no
  # bind ""
  # slowlog-log-slower-than 0(10000)
  # slowlog-max-len 250(128)
  redisSingle:
    image: redis:${REDIS_VERSION}
    container_name: redis-6x-single
    restart: always
    ports:
      - 16379:6379
    volumes:
      - "D:/docker-volumes/redis-${REDIS_VERSION}/data/:/data/"
      - "./redis-${REDIS_VERSION}.conf:/usr/local/etc/redis/redis-${REDIS_VERSION}.conf"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis-${REDIS_VERSION}.conf"