spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_redis?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_redis?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: test-redis-datasource
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      read-only: false
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
    #  hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    hibernate:
      ddl-auto: update
